update
nxgeninventors/simba pull request #23
Opened 2023-04-26 06:48 UTC by Sivakumar-21

2023-04-26 06:51 UTC, muni2explore requested changes

2023-04-26 06:51 UTC, muni2explore commented on app/Models/Client.php
> +        return self::where('is_supplier', true)
where order by

2023-04-26 06:51 UTC, muni2explore commented on app/Http/Controllers/ProjectController.php
> +        $categories = ProjectCategory::getProjectCategory();
reneme getProjectCategories

2023-04-26 06:51 UTC, muni2explore commented on app/Models/Client.php
> +        return self::where('is_supplier', true)
getSuppliers

2023-04-26 06:53 UTC, Sivakumar-21 commented on app/Models/Client.php
> +        return self::where('is_supplier', true)
changed

2023-04-26 06:55 UTC, Sivakumar-21 commented on app/Http/Controllers/ProjectController.php
> +        $categories = ProjectCategory::getProjectCategory();
changed

2023-05-08 10:07 UTC, muni2explore approved these changes
Looks good

2023-05-08 10:07 UTC, merged